package sky.compiler;

import com.squareup.javapoet.ClassName;

/**
 * @author sky
 * @version 1.0 on 2017-10-30 下午7:32
 * @see SkyConsts
 */
public class SkyConsts {

	public static final String		PACKAGE_OF_GENERATE_BIZ_FILE		= "com.sky.android.module.biz";

	public static final String		PACKAGE_OF_GENERATE_DISPLAY_FILE	= "com.sky.android.module.display";

	public static final String		PROJECT								= "Sky";

	public static final String		SEPARATOR							= "$$";

	public static final String		NAME_OF_GROUP						= PROJECT + SEPARATOR + "Biz" + SEPARATOR;

	public static final String		NAME_OF_GROUP_DISPLAY				= PROJECT + SEPARATOR + "Display" + SEPARATOR;

	public static final String		WARNING_TIPS						= "DO NOT EDIT THIS FILE!!! SKY TIPS~~";

	public static final String		FACADE_PACKAGE						= "sky.core.methodModule";

	public static final ClassName	SKY_I_MODULE						= ClassName.get(FACADE_PACKAGE, "SKYIModule");

	public static final ClassName	SKY_I_MODULE_PARAM					= ClassName.get("java.util.concurrent", "ConcurrentHashMap");

	public static final ClassName	SKY_I_MODULE_PARAM_MODEL			= ClassName.get("sky.core.methodModule", "SkyMethodModel");

	public static final ClassName	SKY_I_MODULE_PARAM_METHOD_BIZ		= ClassName.get("sky.core.methodModule", "SkyBizMethod");

	public static final ClassName	SKY_I_MODULE_PARAM_METHOD_DISPLAY	= ClassName.get("sky.core.methodModule", "SkyDisplayMethod");

	public static final String		METHOD_LOAD_INTO					= "loadInto";

	// Java type
	private static final String		LANG								= "java.lang";

	public static final String		BYTE								= LANG + ".Byte";

	public static final String		SHORT								= LANG + ".Short";

	public static final String		INTEGER								= LANG + ".Integer";

	public static final String		LONG								= LANG + ".Long";

	public static final String		FLOAT								= LANG + ".Float";

	public static final String		DOUBEL								= LANG + ".Double";

	public static final String		BOOLEAN								= LANG + ".Boolean";

	public static final String		STRING								= LANG + ".String";

	public static final String		PARCELABLE							= "android.os.Parcelable";
}
